deserializer handler testing
LionWeb-io/lionweb-csharp pull request #26
Opened 2024-08-27 13:02 UTC by erk-dik

Tests covering a subsets of the available deserializar handlers.

2024-08-27 13:34 UTC, dslmeinte requested changes
(draft)

2024-08-27 13:34 UTC, dslmeinte commented on test/LionWeb-CSharp-Test/tests/serialization/DeserializationTests.cs
> +    private class UnknownClassifierHandler(Func<Classifier?> incrementer) : IDeserializerHandler
Would it be an idea to have an abstract `NotImplementedDeserializerHandler` which has every method throw an `NotImplementedException`. Then the `UnknownClassifierHandler` could extend that and just implement `UnknownClassifier`, etc.

2024-08-27 13:34 UTC, dslmeinte commented on test/LionWeb-CSharp-Test/tests/serialization/DeserializationTests.cs
> +    private class UnknownFeatureHandler(Func<Feature?> incrementer) : IDeserializerHandler
The `NotImplementedDeserializerHandler` proposed above would also make things more readable here.

2024-08-27 13:34 UTC, dslmeinte commented on test/LionWeb-CSharp-Test/tests/serialization/DeserializationTests.cs
> +        IDeserializer deserializer = new DeserializerBuilder()
I'm guessing the construction of the `IDeserializer` instances could be DRY'd a bit.

2024-08-27 14:13 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/DeserializationTests.cs
> +    private class UnknownFeatureHandler(Func<Feature?> incrementer) : IDeserializerHandler
This one and similar ones now extend and specialize NotImplementedDeserializerHandler .

2024-10-31 13:46 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnknownClassifierTests.cs
> +/// <see cref="IDeserializerHandler.UnknownClassifier"/>
I don't think this needs / should be inside the `<summary>` tag

2024-10-31 13:47 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnknownClassifierTests.cs
> +    /// Heals by replacing unknown classifier with a known classifier in the language
which language?

2024-11-06 18:48 UTC, enikao commented on src/LionWeb-CSharp/core/M1/IDeserializerHandler.cs
> +    /// <remarks>if returned replacement node id is not unique, deserializer keeps looking for an unique node id, this may lead to an infinite loop </remarks>
deserializer keeps calling this method, that might be the infinite loop

2024-11-06 18:52 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    public void direct_circular_containment_heals_case_2()
explain in docs what's the difference to the test above

2024-11-06 18:54 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    /// Direct circular dependency: A has B, C as children. B has C as a child. C has A as a child.
`B` has `D` as child I think?

2024-11-06 18:55 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    /// Direct circular dependency: A has B, C as children. B has C as a child. C has A as a child.
`B` has `D` as child

2024-11-06 18:55 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    public void direct_circular_containment_multiple_children_heals_case_2()
explain difference to previous test

2024-11-06 18:55 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    public void indirect_circular_containment_case_2()
explain difference to previous test

2024-11-06 18:58 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +                    Parent = null
Why not `A`?

2024-11-06 19:05 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/DuplicateContainmentTests.cs
> +    public void duplicate_containment_keeps_existing_parent()
this class is already named `DuplicateContainment`, no need to repeat in method name

2024-11-06 19:07 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/DuplicateContainmentTests.cs
> +    public void duplicate_containment_keeps_existing_parent()
Both parents are existing parents. It again depends on the processing order which one comes first (similar to circular containment).

2024-11-06 19:09 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidAnnotationTests.cs
> +}
Add another test: Heal with another invalid annotation

2024-11-06 19:10 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidFeatureTests.cs
> +    public void invalid_feature_does_not_heal()
maybe add docs: existing feature in wrong classifier

2024-11-06 19:11 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidFeatureTests.cs
> +    public void invalid_feature_does_not_heal()
or adjust method name

2024-11-06 19:15 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/SkipDeserializingDependentNodeTests.cs
> +    [Ignore(
didn't we do this by now?

2024-11-06 19:17 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnknownFeatureTests.cs
> +    }
add tests that heal to invalid feature

2024-11-06 19:18 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/DuplicateNodeIdTests.cs
> +    }
add test that heals the first time to still duplicate node, only works the second time

2024-11-06 19:19 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidFeatureTests.cs
> +    }
add tests that heal to invalid feature

2024-11-06 19:19 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidLinkValueTests.cs
> +    }
add tests that heal to invalid value

2024-11-06 19:20 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnknownEnumerationLiteralTests.cs
> +    }
add test that heals to invalid value

2024-11-06 19:21 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnresolvableAnnotationTests.cs
> +    }
add test that heals to invalid annotation

2024-11-06 19:21 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnresolvableChildTests.cs
> +    }
add test that heals to invalid child

2024-11-06 19:21 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnresolvableReferenceTargetTests.cs
> +    }
add test that heals to invalid target

2024-11-06 19:22 UTC, enikao commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnresolvableReferenceTargetTests.cs
> +}
add test that heals based on the correct ResolveInfo

2024-11-06 19:23 UTC, enikao reviewed
very thorough work! Some proposals for testing failure cases.

2024-11-07 08:58 UTC, erk-dik commented on src/LionWeb-CSharp/core/M1/IDeserializerHandler.cs
> +    /// <remarks>if returned replacement node id is not unique, deserializer keeps looking for an unique node id, this may lead to an infinite loop </remarks>
correct, fixed.

2024-11-07 09:04 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    public void direct_circular_containment_heals_case_2()
added explanation in xdoc.

2024-11-07 09:07 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    /// Direct circular dependency: A has B, C as children. B has C as a child. C has A as a child.
corected.

2024-11-07 09:08 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    /// Direct circular dependency: A has B, C as children. B has C as a child. C has A as a child.
corrected/.

2024-11-07 09:23 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    public void direct_circular_containment_multiple_children_heals_case_2()
added.

2024-11-07 09:25 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/CircularContainmentTests.cs
> +    public void indirect_circular_containment_case_2()
added.

2024-11-07 09:57 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/DuplicateContainmentTests.cs
> +    public void duplicate_containment_keeps_existing_parent()
got your point, I use now the wording "current parent" instead od existing parent.

2024-11-07 10:03 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/DuplicateContainmentTests.cs
> +    public void duplicate_containment_keeps_existing_parent()
actually, i see no harm with repating here, also by reading method names,  i can differentiate tests related to containment and annotation.

2024-11-07 10:25 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidFeatureTests.cs
> +    public void invalid_feature_does_not_heal()
actually here we use existing feature in wrong feature type (key-r is property, we use it in reference), docs added.

2024-11-07 11:23 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidAnnotationTests.cs
> +}
added

2024-11-07 12:52 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnknownFeatureTests.cs
> +    }
added.

2024-11-07 13:10 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidFeatureTests.cs
> +    }
added.

2024-11-07 13:17 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidLinkValueTests.cs
> +    }
added.

2024-11-07 13:21 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/InvalidPropertyValueTests.cs
> +    }
added.

2024-11-07 13:32 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnknownEnumerationLiteralTests.cs
> +    }
added.

2024-11-07 13:55 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnresolvableAnnotationTests.cs
> +    }
added.

2024-11-07 13:59 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnresolvableChildTests.cs
> +    }
added.

2024-11-07 14:03 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnresolvableReferenceTargetTests.cs
> +    }
added.

2024-11-07 14:07 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/UnresolvableReferenceTargetTests.cs
> +}
added

2024-11-07 14:54 UTC, erk-dik commented on test/LionWeb-CSharp-Test/tests/serialization/deserialization/customHandler/DuplicateNodeIdTests.cs
> +    }
added

2024-11-07 14:56 UTC, erk-dik commented
> Very general idea, not sure whether you want to implement it due to timing:
> 
> 1. The tests get very long, maybe we can build our own small internal "mini-DSL" to create serialized nodes? Could look similar as the language building mini-DSL in `ShapesDefinition.cs`
> 2. Currently we're checking the outcome of deserialization by a big bunch of asserts. Maybe we could just create the expected node model and use `Comparer` to assert they're equal?

I will implement those in seperate branches.

2024-11-07 20:06 UTC, enikao commented
for all Link-based tests: Please add a test that we can handle multiple entries.

2024-11-07 20:24 UTC, enikao commented
Depends on https://github.com/gragra33/Utf8JsonAsyncStreamReader/issues/3

2024-11-08 12:27 UTC, enikao commented
See also https://github.com/LionWeb-io/lionweb-csharp/issues/34

2024-11-09 12:31 UTC, enikao approved these changes

2024-11-15 12:42 UTC, merged